services:
  api:
    build: .
    container_name: api
    ports: 
      - "8080:8080"
    restart: always
    networks:
      - net
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15.2-alpine
    container_name: db
    networks:
      - net
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: anothapp_db
    volumes: 
      - ./pgdata:/var/lib/postgresql/data
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    healthcheck:
      test: pg_isready -d anothapp
      retries: 10
    
networks:
  net: